version: "3.0"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"