<?php
namespace Swordfish\CLI\Tests;

use PHPUnit\Framework\TestCase;

/**
 * Cross-compatibility tests verifying that the CLI and SPA crypto modules
 * are byte-compatible: a secret encrypted by one can be decrypted by the other.
 *
 * The shared test vectors below are pinned against the known v1 values used in
 * the SPA crypto test suite (frontend/src/__tests__/crypto.test.ts).
 */
class CrossCompatTest extends TestCase
{
    // Known v1 test vectors — identical to those in frontend/src/__tests__/crypto.test.ts.
    // Passphrase and plaintext are fixed; salt and nonce are deterministic so the
    // ciphertext is reproducible by both the CLI (libsodium/PHP) and the SPA (WebCrypto).
    private const PASSPHRASE = 'correct-horse-battery-staple';
    private const PLAINTEXT  = 'Hello, Swordfish!';
    private const SALT_HEX   = '00112233445566778899aabbccddeeff';
    private const NONCE_HEX  = '000102030405060708090a0b';
    // AES-256-GCM ciphertext (plaintext + 16-byte auth tag) produced by both implementations
    private const CIPHERTEXT_HEX = '1c583908cb62ca193b7977a6b076f83e58efe562d06358fc4cd77241fb958081d3';
    // Server blob format: hex(salt || nonce || ciphertext)
    private const BLOB = self::SALT_HEX . self::NONCE_HEX . self::CIPHERTEXT_HEX;
    // Verifier: PBKDF2-SHA-256(passphrase, pepper, 10000 iterations) as hex
    private const VERIFIER_HEX = 'ed6872e5db3e4c06b0dfb76eca49a7b4241020a06d5c81d04d09340a3c23c888';

    /**
     * CLI can decrypt a blob produced by the SPA.
     *
     * The blob was generated by the SPA WebCrypto module using the fixed salt and
     * nonce above. The CLI must recover the original plaintext using its own
     * libsodium-based decryption path.
     */
    public function testCliDecryptsSpaBlob(): void
    {
        $decoded    = hex2bin(self::BLOB);
        $salt       = substr($decoded, 0, 16);
        $nonce      = substr($decoded, 16, SODIUM_CRYPTO_AEAD_AES256GCM_NPUBBYTES);
        $ciphertext = substr($decoded, 16 + SODIUM_CRYPTO_AEAD_AES256GCM_NPUBBYTES);

        $key       = hash_pbkdf2('sha256', self::PASSPHRASE, $salt, 10000, 32, true);
        $decrypted = sodium_crypto_aead_aes256gcm_decrypt($ciphertext, '', $nonce, $key);

        $this->assertSame(self::PLAINTEXT, $decrypted);
    }

    /**
     * CLI encryption with fixed inputs produces the same blob as the SPA.
     *
     * When the CLI uses the same salt and nonce as the SPA test vectors, it must
     * emit an identical hex blob. This confirms byte-level compatibility in the
     * encrypt direction (CLI → SPA).
     */
    public function testCliEncryptionMatchesSpaVectors(): void
    {
        $salt  = hex2bin(self::SALT_HEX);
        $nonce = hex2bin(self::NONCE_HEX);

        $key        = hash_pbkdf2('sha256', self::PASSPHRASE, $salt, 10000, 32, true);
        $ciphertext = sodium_crypto_aead_aes256gcm_encrypt(self::PLAINTEXT, '', $nonce, $key);

        $blob = bin2hex($salt . $nonce . $ciphertext);

        $this->assertSame(self::BLOB, $blob);
    }

    /**
     * CLI verifier matches the SPA verifier for the same passphrase.
     *
     * Both implementations derive the verifier via PBKDF2-SHA-256 over the shared
     * pepper. The hex output must be identical so the server can authenticate
     * requests from either client.
     */
    public function testCliVerifierMatchesSpaVerifier(): void
    {
        $verifier = hash_pbkdf2('sha256', self::PASSPHRASE, SWORDFISH_PEPPER, 10000);

        $this->assertSame(self::VERIFIER_HEX, $verifier);
    }
}
