apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swordfish.fullname" . }}
  labels:
    {{- include "swordfish.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "swordfish.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swordfish.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}{{ if .Values.server.image.sha }}-{{ .Values.server.image.sha }}{{ end }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: {{ .Values.server.env.SERVER_PORT | quote }}
            - name: REDIS_HOST
              value: {{ include "swordfish.fullname" . }}-redis-master
            - name: REDIS_PORT
              value: "6379"
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 