{{- if .Values.server.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swordfish.fullname" . }}-pull-secret
  labels:
    {{- include "swordfish.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"ghcr.io\": {\"auth\": \"%s\"}}}" (printf "%s:%s" .Values.server.imagePullSecrets.github.username .Values.server.imagePullSecrets.github.token | b64enc) | b64enc }}
{{- end }} 