apiVersion: v1
kind: Service
metadata:
  name: {{ include "swordfish.fullname" . }}
  labels:
    {{- include "swordfish.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "swordfish.selectorLabels" . | nindent 4 }} 