import { describe, it, expect } from 'vitest'
import { encrypt, decrypt, getVerifier } from '../crypto'

/**
 * Cross-compatibility tests verifying that the SPA and CLI crypto modules
 * are byte-compatible: a secret encrypted by one can be decrypted by the other.
 *
 * The shared test vectors below are pinned against the known v1 values used in
 * the CLI crypto test suite (cli/tests/CrossCompatTest.php).
 */

// Known v1 test vectors — identical to those in cli/tests/CrossCompatTest.php.
// Passphrase and plaintext are fixed; salt and nonce are deterministic so the
// ciphertext is reproducible by both the SPA (WebCrypto) and the CLI (libsodium/PHP).
const VECTORS = {
  passphrase: 'correct-horse-battery-staple',
  plaintext: 'Hello, Swordfish!',
  saltHex: '00112233445566778899aabbccddeeff',
  nonceHex: '000102030405060708090a0b',
  // AES-256-GCM ciphertext (plaintext + 16-byte auth tag) produced by both implementations
  ciphertextHex: '1c583908cb62ca193b7977a6b076f83e58efe562d06358fc4cd77241fb958081d3',
  // Server blob format: hex(salt || nonce || ciphertext)
  get blob() {
    return this.saltHex + this.nonceHex + this.ciphertextHex
  },
  // Verifier: PBKDF2-SHA-256(passphrase, pepper, 10000 iterations) as hex
  verifierHex: 'ed6872e5db3e4c06b0dfb76eca49a7b4241020a06d5c81d04d09340a3c23c888',
}

describe('CLI ↔ SPA cross-compatibility', () => {
  it('SPA decrypts a blob produced by the CLI', async () => {
    // The blob was generated by the CLI (libsodium/PHP) using the fixed salt and
    // nonce above. The SPA must recover the original plaintext using WebCrypto.
    const result = await decrypt(VECTORS.blob, VECTORS.passphrase)
    expect(result).toBe(VECTORS.plaintext)
  })

  it('SPA encryption with fixed inputs produces the same blob as the CLI', async () => {
    // Inject fixed salt and nonce by constructing the blob manually from the
    // SPA encrypt output, then verify the ciphertext portion matches the CLI vector.
    // We do this by encrypting with the SPA and checking the ciphertext bytes match
    // when the same salt and nonce are used via a direct WebCrypto call.
    const saltBytes = new Uint8Array(
      VECTORS.saltHex.match(/.{2}/g)!.map(b => parseInt(b, 16)),
    )
    const nonceBytes = new Uint8Array(
      VECTORS.nonceHex.match(/.{2}/g)!.map(b => parseInt(b, 16)),
    )

    const passkey = await globalThis.crypto.subtle.importKey(
      'raw',
      new TextEncoder().encode(VECTORS.passphrase),
      { name: 'PBKDF2' },
      false,
      ['deriveKey'],
    )
    const key = await globalThis.crypto.subtle.deriveKey(
      { name: 'PBKDF2', salt: saltBytes, iterations: 10000, hash: 'SHA-256' },
      passkey,
      { name: 'AES-GCM', length: 256 },
      false,
      ['encrypt'],
    )
    const ciphertext = await globalThis.crypto.subtle.encrypt(
      { name: 'AES-GCM', iv: nonceBytes },
      key,
      new TextEncoder().encode(VECTORS.plaintext),
    )

    const ciphertextHex = Array.from(new Uint8Array(ciphertext))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('')

    expect(ciphertextHex).toBe(VECTORS.ciphertextHex)
  })

  it('SPA verifier matches the CLI verifier for the same passphrase', async () => {
    // Both implementations derive the verifier via PBKDF2-SHA-256 over the shared
    // pepper. The hex output must be identical so the server can authenticate
    // requests from either client.
    const verifier = await getVerifier(VECTORS.passphrase)
    expect(verifier).toBe(VECTORS.verifierHex)
  })
})
