apiVersion: v2
name: swordfish
description: A secure, anonymous secret sharing application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "18.19.4"
    repository: "https://charts.bitnami.com/bitnami" 