nameOverride: ""
fullnameOverride: ""

server:
  replicaCount: 1
  image:
    repository: ghcr.io/displacetech/swordfish/server
    tag: "latest"
    sha: ""
    pullPolicy: Always
  # Image pull secrets configuration
  imagePullSecrets:
    # -- Create a pull secret using provided credentials
    create: false
    # -- Name of existing pull secret to use
    name: ""
    # -- GitHub credentials if creating pull secret
    github:
      username: ""
      token: ""
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
    SERVER_PORT: "8080"

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false  # Ephemeral storage since secrets expire in 24h anyway
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: swordfish.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] 